name: manual-parameterized
on:
        workflow_dispatch:
                inputs:
                        application_name:
                                type: string
                                required: true
                        run_validation:
                                type: boolean
                                required: true
jobs:
        validate:
                outputs:
                        validate_status: ${{ steps.set-status.outputs.validate_status }}
                runs-on: ubuntu-latest
                steps:
                      - name: inputs
                        run: |
                                echo "Application Name: ${{ inputs.application_name }}"
                                echo "Run Validation: ${{ inputs.run_validation }}"

                      - name: set status
                        id: set-status
                        # Using GH expression syntax avoids string matching bugs in bash
                        run: |
                                if [ "${{ inputs.run_validation }}" = "true" ]; then
                                        echo "validate_status=success" >> $GITHUB_OUTPUT
                                else
                                        echo "validate_status=skipped" >> $GITHUB_OUTPUT
                                fi

        summary:       
                runs-on: ubuntu-latest
                needs: validate
                if: needs.validate.outputs.validate_status == 'success'
                steps:
                        - name: sum
                          run: echo "summary"
